package com.matin.taxi.db.model;

import java.sql.Timestamp;

/*
 drop table  taxi.Message
CREATE TABLE taxi.Message (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	int state   ,
	created_at TIMESTAMP DEFAULT NOW(),
	personId int4 NULL,
	taxiId int4 NULL,
	message text NULL,
	CONSTRAINT position_pkey PRIMARY KEY (id)

	--,CONSTRAINT fk_person    FOREIGN KEY(personId)      REFERENCES person(id)
);
*/

public class Messages {
	private Long id;
	private int state;
	private Long context;
	private Long from;
	private Long to;
	private String message;
	private Timestamp created_at;

	public Messages() {}

	public Messages(int state ,Long context,Long from,Long to ,String message) {
		this.state=state;
		this.context=context;
		this.from=from;
		this.to=to;
		this.message=message;
	}

	public Long getId() {return id;}
	public void setId(Long id) {this.id = id;}

	public int getState() {return state;}
	public void setState(int state) {this.state = state;}

	public Long getContext() { return context; }
	public void setContext(Long context) { this.context = context;	}

	public Long getFrom() {	return from;}
	public void setFrom(Long from) {this.from = from;}

	public Long getTo() { return to; }
	public void setTo(Long to) { this.to = to;}
	
	public String getMessage() {return message;}
	public void setMessage(String message) {this.message = message;	}

	public Timestamp getCreated_at() {return created_at;}
	public void setCreated_at(Timestamp created_at) {	this.created_at = created_at;}

}
