package com.matin.taxi.db.model;

import java.sql.Timestamp;

/*
 drop table  taxi.Message
CREATE TABLE taxi.Message (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	state int    ,
	created_at TIMESTAMP DEFAULT NOW(),
	personId int4 NULL,
	taxiId int4 NULL,
	message text NULL,
	CONSTRAINT pessage_pkey PRIMARY KEY (id)

	--,CONSTRAINT fk_person    FOREIGN KEY(personId)      REFERENCES person(id)
);

*/

/** DDL
 -- taxi.message definition

-- Drop table

-- DROP TABLE taxi.message;

CREATE TABLE taxi.message (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	state int4 NULL,
	orderId int4 NULL,
	created_at timestamp DEFAULT now() NULL,
	personid int4 NULL,
	taxiid int4 NULL,
	message text NULL,
	CONSTRAINT pessage_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE taxi.message OWNER TO nominatim;
GRANT ALL ON TABLE taxi.message TO nominatim;
 */

public class Messages {
	
	private Long id;
	private int state;
	private Long orderId;
	private Long from;
	private Long to;
	private String message;
	private Timestamp created_at;

	public Messages() {}

	public Messages(int state ,Long orderId,Long from,Long to ,String message) {
		this.state=state;
		this.orderId=orderId;
		this.from=from;
		this.to=to;
		this.message=message;
	}

	public Long getId() {return id;}
	public void setId(Long id) {this.id = id;}

	public int getState() {return state;}
	public void setState(int state) {this.state = state;}

	public Long getOrderId() { return orderId; }
	public void setOrderId(Long context) { this.orderId = orderId;	}

	public Long getFrom() {	return from;}
	public void setFrom(Long from) {this.from = from;}

	public Long getTo() { return to; }
	public void setTo(Long to) { this.to = to;}
	
	public String getMessage() {return message;}
	public void setMessage(String message) {this.message = message;	}

	public Timestamp getCreated_at() {return created_at;}
	public void setCreated_at(Timestamp created_at) {	this.created_at = created_at;}
	
	@Override
	public String toString() {
		return "Messages [id=" + id + ", state=" + state + ", orderId=" + orderId + ", from=" + from + ", to=" + to
				+ ", message=" + message + ", created_at=" + created_at + "]";
	}

}
