package com.matin.taxi.db.model;

import java.sql.Timestamp;

/*
 drop  TABLE taxi.orders 

create  TABLE taxi.orders  (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	clientId int4  NOT NULL,
	taxiId int4   NULL,
	state int NULL,
	route text NULL,
	createTime timestamp NULL,
	
	clientStartTime timestamp NULL,
	acceptedTime timestamp NULL,
	taxiStartTime timestamp NULL,
	endTime timestamp NULL,
	
	
	
	CONSTRAINT order_pkey PRIMARY KEY (id)
);

2025/02/13 13:17:02

ADD CREATE EXTENSION IF NOT EXISTS tablefunc;

 */

public class Orders {
	public static int STATE_DELETED=-1;//TEMPLATE   
	public static int STATE_CREATED=0;//TEMPLATE   
	public static int STATE_CLIENT_START =1;
	public static int STATE_TAXI_ACCEPTED=2;
	public static int STATE_TAXI_START=3;
	public static int STATE_TAXI_END=4;
	
	public static int STATE_EXPIRED=5;
	
	

	Long id;
	Long clientId; 
	Long taxiId ;
	int state ;
	String route ;
	Timestamp createTime  ; 
	
	Timestamp clientStartTime;
	Timestamp acceptedTime;
	Timestamp taxiStartTime;
	Timestamp endTime;
	
	public Orders() {
	
	}
	public Orders( Long clientId, Long taxiId, int state, String route) {
		super();
		
		this.clientId = clientId;
		this.taxiId = taxiId;
		this.state = state;
		this.route = route;
		
	}
	
	
	public Orders(Long id, Long clientId, Long taxiId, int state, String route, Timestamp createTime) {
		super();
		this.id = id;
		this.clientId = clientId;
		this.taxiId = taxiId;
		this.state = state;
		this.route = route;
		this.createTime = createTime;
	}
	
	
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Long getClientId() {
		return clientId;
	}
	public void setClientId(Long clientId) {
		this.clientId = clientId;
	}
	public Long getTaxiId() {
		return taxiId;
	}
	public void setTaxiId(Long taxiId) {
		this.taxiId = taxiId;
	}
	public int getState() {
		return state;
	}
	public void setState(int state) {
		this.state = state;
	}
	public String getRoute() {
		return route;
	}
	public void setRoute(String route) {
		this.route = route;
	}
	public Timestamp getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}
	
	public Timestamp getClientStartTime() {
		return clientStartTime;
	}
	public void setClientStartTime(Timestamp clientStartTime) {
		this.clientStartTime = clientStartTime;
	}
	public Timestamp getAcceptedTime() {
		return acceptedTime;
	}
	public void setAcceptedTime(Timestamp acceptedTime) {
		this.acceptedTime = acceptedTime;
	}
	public Timestamp getTaxiStartTime() {
		return taxiStartTime;
	}
	public void setTaxiStartTime(Timestamp taxiStartTime) {
		this.taxiStartTime = taxiStartTime;
	}
	public Timestamp getEndTime() {
		return endTime;
	}
	public void setEndTime(Timestamp endTime) {
		this.endTime = endTime;
	}
	
	@Override
	public String toString() {
		return "Orders [id=" + id + ", clientId=" + clientId + ", taxiId=" + taxiId + ", state=" + state + ", route="
				+ route + ", createTime=" + createTime + "]";
	}
	
	
}
