package com.matin.taxi.db.model;

import java.sql.Timestamp;
/*
 create schema taxi
drop table  taxi.position
CREATE TABLE taxi.position (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at TIMESTAMP DEFAULT NOW(),
	personId int4 NULL,
	position text NULL,
	CONSTRAINT position_pkey PRIMARY KEY (id)

	,CONSTRAINT fk_person    FOREIGN KEY(personId)      REFERENCES person(id)
	--FOREIGN KEY(personId)        REFERENCES person(id)
);


select * from person

INSERT INTO taxi.position (  personid, position) 
VALUES( 1,  'dsdddsd');


SELECT * FROM taxi.position 
WHERE id = (SELECT MAX(ID) FROM taxi.position where personId=1 );

 */

public class Position {

	private Long id;
	private Long personId;
	private String position;
	private Timestamp created_at;
	
	public Long getId() { return id;	}
	public void setId(Long id) { this.id = id;}
	public Long getPersonId() {	return personId;}
	public void setPersonId(Long personId) { this.personId = personId; }
	public String getPosition() { return position;}
	public void setPosition(String position) { this.position = position; }
	public Timestamp getCreated_at() {return created_at;	}
	public void setCreated_at(Timestamp timestamp) { this.created_at = timestamp;	}

}
