package com.matin.taxi.db.model;

import java.sql.Timestamp;

/**
 -- taxi.proffer definition
-- DROP TABLE taxi.proffer;

CREATE TABLE taxi.proffer (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	state int4 NULL,
	orderId int4 NULL,
	personId int4 NULL,
	message text NULL,
	created_at timestamp DEFAULT now() NULL,
	CONSTRAINT fk_department FOREIGN KEY (orderId)
	REFERENCES taxi.orders(id)
);

-- Permissions

ALTER TABLE taxi.proffer OWNER TO nominatim;
GRANT ALL ON TABLE taxi.proffer TO nominatim;
 **/

/*
 * state 
 * 	0-create
 * 	1-assigned 
 *  2-approved
 *  3-closed 
 */

public class Proffer {

	public static int CREATE =0;
	public static int ASSIGNED=1; 
	public static int APPROVED=2;
	public static int CLOSED =3;
	
	private int id;
	private int state;
	private Long orderId;
	
	private Long personId;
	
	private String message;
	private Timestamp created_at;
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public int getState() {
		return state;
	}
	public void setState(int state) {
		this.state = state;
	}
	public Long getOrderId() {
		return orderId;
	}
	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}
	
	public Long getPersonId() {
		return personId;
	}
	public void setPersonId(Long personId) {
		this.personId = personId;
	}
	
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	public Timestamp getCreated_at() {
		return created_at;
	}
	public void setCreated_at(Timestamp created_at) {
		this.created_at = created_at;
	}
	
}
